replicaCount: 1
appsVars:
  appNameMongo: mongo
  appNameFront: front
  appNameApi: api
  appPortMongo: 27017
  appPortFront: 80
  appPortApi: 80
appsImages:
  appRepoMongo: mongo
  appRepoTagMongo: latest
  appRepoFront: otomato/maskshop-front
  appRepoTagFront: latest
  appRepoApi: otomato/maskshop-api
  appRepoTagApi: latest
image:
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
