name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  #FRONT_IMAGE_NAME: image
    INITDB: "true"  

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "TODO - deploy to a cluster and verify"
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Calculate tag
        run: |
          TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && TAG=$(echo $TAG | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$TAG" == "master" ] && TAG=latest
      - name: Build image
        run: docker-compose build

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker-compose push
